### ISSUE TITLE
Bug: Url field validating server side with no content

### ISSUE THREAD

**Issue by mbarlock** [punchcard-cms/content-types#102]
With a `type: url` field, the value is validated on the server when there is nothing in the input causing a "Not a valid url." error

## Steps for Reproducing

- Create an input with `type: url` without a `required` field
- In punchcard UI, don't input anything into the `url` field
- "Not a valid url." appears and prevents submitting

## Affected Browsers

- [ ] All browsers 😢 

## Runtime Version
node 4.4.3

## Code Version
5.0.0

**Comment by scottnath** [comment]
Issue moved to [punchcard-cms/input-plugin-url #46](https://github.com/punchcard-cms/input-plugin-url/issues/46) via [**ZenHub**](https://www.zenhub.com/)
