### ISSUE TITLE
Bug: Duplicate Required Titles

### ISSUE THREAD

**Issue by Snugug** [punchcard-cms/content-types#127]
Multi-input input plugins that are set to required get all of their marks stacked up on the first input
## Steps for Reproducing
- Create content type with required to save or required to publish field set for a multi-input input input plugin
- Render HTML form
- Note the first input gets all of the marks
## Screenshots

![Stacked required labels](https://cloud.githubusercontent.com/assets/377188/19284515/2af473ea-8fc4-11e6-8a7e-4dbee50e2e4d.png)
## Affected Browsers
- [ ] All
## Runtime Version

All
## Code Version

Latest

**Comment by ineedsubstance** [comment]
This was already fixed here: https://github.com/punchcard-cms/punchcard/issues/530
